### ISSUE TITLE
Terraform source raw image for the root image

### ISSUE THREAD

**Issue by madpearl** [SriRamanujam/okd-deployment#1]
Hello Sri,
 You have in ansible new destination for the raw file "/var/lib/libvirt/images/fedora-coreos-{{ coreos_version }}-qemu.x86_64.raw". You didn't change it in the terraform/modules/fcos-base/main.tf , it is the old path { source = "/var/tmp/fedora-coreos-${var.fcos_version}-qemu.x86_64.raw" } . the right one should be as is in the ansible-playbook 
 
 - name: Convert qcow2 to raw image file in /var/lib/libvirt/images
Best Regards
Bisser Danev

**Comment by SriRamanujam** [comment]
Thanks very much for the catch :)
